### ISSUE TITLE
Share Link error on Safari, doesn't copy

### ISSUE THREAD

**Issue by ReeceM** [gawlk/quickbook#1]
Hi,

Not sure if you haven't gotten around to it, you did say it was buggy on discord😄 

Clicking the link/share icon throws an error on safari.

```
[Error] TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')
	(anonymous function) (main.js:69:557427)
	(anonymous function) (main.js:1:9977)
	forEach
	(anonymous function) (main.js:1:9966)
	(anonymous function) (main.js:7:33194)
```

The copy to clipboard code might not be cross compatible. As this is only what I noticed on a Safari browser Version 12.1.2 (yeah, I know).

**Comment by gawlk** [comment]
I did not get around it actually, thank you !

**Comment by gawlk** [comment]
Should be fixed in the latest commit

**Comment by ReeceM** [comment]
Is working 👍
